/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f9f9fb',
        surface: '#f9f9fb',
        'surface-white': '#ffffff',
        'surface-dim': '#d9dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f5',
        'surface-container': '#edeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e4',
        'on-surface': '#1a1c1d',
        'on-surface-variant': '#434654',
        'on-background': '#1a1c1d',
        outline: '#737686',
        'outline-variant': '#c3c6d7',
        primary: '#003ca7',
        'on-primary': '#ffffff',
        'primary-container': '#1152d4',
        'on-primary-container': '#cad5ff',
        'inverse-primary': '#b4c5ff',
        'primary-glow': 'rgba(17, 82, 212, 0.20)',
        secondary: '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#d3e4fe',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed': '#00174c',
        'slate-900': '#0f172a',
        'slate-800': '#1e293b',
        'slate-200': '#e2e8f0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'container-max': '480px',
        'gutter-default': '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1.25rem',
        'stack-lg': '2rem',
        'inset-card': '2.5rem',
        'inset-card-mobile': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '900' }],
        'display-hero-mobile': ['32px', { lineHeight: '1.2', fontWeight: '900' }],
        'headline-md': ['20px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-base': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-bold': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        'caption-bold': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
